apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-inventory
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: MS-INI01-02
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MS_ID
              value: {{ .Values.env.microserviceId | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory
spec:
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - port: {{ .Values.service.port }}
